<TransactionScreen>:
    canvas.before:
        Color:
            rgba: 0.97, 0.98, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size

<RegularScreen>:
    canvas.before:
        Color:
            rgba: 0.97, 0.98, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size

<GoalScreen>:
    canvas.before:
        Color:
            rgba: 0.97, 0.98, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size